### ISSUE TITLE
KeyError: ‘endpoint_resolver’ when using multiple cameras

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#12]
When configuring multiple rekognition sensors you may get the error `KeyError: ‘endpoint_resolver’`. [This arises from the boto3 library](https://github.com/boto/boto3/issues/801) which this component uses, and occurs when multiple requests for a `session` object are made by boto3, which presumably happens when you multiple rekognition sensors. I don't have a solution for this yet

**Comment by jtscott** [comment]
Hi Rob,

Just wanted to ask here instead of potentially opening a duplicate. I am only getting the first camera saving to the snapshot folder when save_file_folder is configured:
```
image_processing:
  - platform: amazon_rekognition
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: us-west-2
    save_file_folder: !secret snapshot_folder
    target: Person
    source:
      - entity_id: camera.front_door_still
      - entity_id: camera.back_door_still
```
Where snapshot folder is:
`snapshot_folder: '/config/www/snapshot/'`

The file `rekognition_person_front_door_latest.jpg` is created in that folder, but back_door does not.

Thanks!
