### ISSUE TITLE
Number of detected target objects is sometimes wrong

### ISSUE THREAD

**Issue by eslavnov** [robmarkcole/HASS-amazon-rekognition#19]
Hey @robmarkcole, thanks for an awesome component!

It works great, however sometimes the sensor returns 0 despite the fact that a target was found:
![image](https://user-images.githubusercontent.com/30501641/74941719-d1308e00-53f3-11ea-82a3-bfe7491322fa.png)

I also saw somebody mentioning this issue [here ](https://community.home-assistant.io/t/object-detection-with-amazon-rekognition/86358/78).

I've investigated and it seems that sometimes `label["Instances"]` is returned as `[]` from AWS despite the match. Here is how it looks in my particular case:
`{'Name': 'Pet', 'Confidence': 67.64640045166016, 'Instances': [], 'Parents': [{'Name': 'Animal'}]}`

Can you maybe add an extra check if len(label["Instances"]) == 0 and return 1 in these cases instead?

Thanks in advance!

**Comment by robmarkcole** [comment]
Change config:
```
confidence: 50 # Optional, default is 80
```

**Comment by eslavnov** [comment]
I thought `confidence` is used only for bounding boxes according to the README?

Anyways, I've tried adding it to config with a value of 50 (and also 10) - same issue, the sensor returns 0.

**Comment by robmarkcole** [comment]
Can you post your config please

**Comment by eslavnov** [comment]
Sure:
```yaml
image_processing:
  - platform: amazon_rekognition
    aws_access_key_id: AWS_ACCESS_KEY_ID
    aws_secret_access_key: AWS_SECRET_ACCESS_KEY
    region_name: eu-west-1
    confidence: 50
    target: Pet
    source:
      - entity_id: camera.local_file
```

I've done some digging and according to [AWS docs](https://docs.aws.amazon.com/rekognition/latest/dg/API_Label.html#rekognition-Type-Label-Instances), "If Label represents an object, Instances contains the bounding boxes for each instance of the detected object. Bounding boxes are returned for common object labels such as people, cars, furniture, apparel or pets.". 

So if I understand it correctly, Instances are not returned for ALL detected objects, but rather for "common" ones. Probably that's why I am having trouble with 'Pet' and another user with 'Baby'.
