### ISSUE TITLE
Multiple targets looks fail for the second one and following

### ISSUE THREAD

**Issue by somar05** [robmarkcole/HASS-amazon-rekognition#42]
First, thanks for this component. Regarding v2.0:
Sensor looks that only show 1 for the first target. For the second and following it show 0. I mean, if the fisrt target is “person” and the second one is “animal”, the sensor show 1 when identify a person and it mark it with the bounded box. But for the “animal” target (the second one) the sensor always is “0”. It looks that only the first target is taked into a account, at least wiht my testing.

**Comment by robmarkcole** [comment]
Everything is fine in testing. Can you provide your (anonymised) config and some screen shots please

**Comment by somar05** [comment]
Config and a screenshot. Maybe this could be related with how the Amazon Rekognition make the counts? No idea

```
image_processing:
  - platform: amazon_rekognition
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: eu-west-1 # Optional region, default is us-east-1
    save_file_folder: /config/www/amazon-rekognition/ # Optional, image storage location
    save_timestamped_file: True # Set True to save timestamped images, default False
    confidence: 50 # Optional, default is 80. Only used for bounding boxes atm
    targets:
      - Person # Optional target object, default Person
      - animal
      - toy
    source:
      - entity_id: `camera.camara_entrada
```

![Scrsh1](https://user-images.githubusercontent.com/38601295/80989999-fe5add00-8e35-11ea-9832-e0d359bfda7a.jpg)
