### ISSUE TITLE
nothing is detected when more than 1 target is configured

### ISSUE THREAD

**Issue by isbkch** [robmarkcole/HASS-amazon-rekognition#74]
I have the following configuration to detect a car, cat or a person from my front door camera

```
- platform: amazon_rekognition
  aws_access_key_id: !secret aws_access_key
  aws_secret_access_key: !secret aws_secret_access_key
  region_name: us-east-1 # Optional region, default is us-east-1
  save_file_folder: /config/www/amazon-rekognition/camera_front_door # Optional, image storage location
  save_timestamped_file: True # Set True to save timestamped images, default False
  confidence: 80 # Optional, default is 80
  targets:
    - car
    - cat
    - person
  source:
    - entity_id: camera.camera_front_door
```
But state is always 0 unless I chose 1 target instead of 3...
What am I doing wrong ?
