### ISSUE TITLE
Add option to save timestamped image to S3 bucket

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#78]
As title, to save the timestamped images. Use a key format `prefix/camera_name/date/` and config like:

```yaml
s3: 
  - bucket: bla
    prefix: foo
```

see https://github.com/robmarkcole/HASS-S3/blob/master/custom_components/s3/__init__.py

There are various tools for displaying images from an S3 bucket
